### PR TITLE
Parse the 'oneway' modifier that can be applied to functions in a service

### LINKED ISSUE #1: Handle the 'oneway' modifier for service functions
The parser is currently ignoring this keyword.

### PR DESCRIPTION
**Pull request by kevinbgreene**
fixes #1

### CODE REVIEW

**Review by phated — CHANGES_REQUESTED** [review]
I believe `oneway` should only parse if followed by a `void` return type.  It currently parses with any return type.

Also, should the `oneway` AST result be an object with a `type`, `value` and `loc`?  It doesn't highlight as I was expecting in the AST Explorer when only a boolean.

**Comment by kevinbgreene** [comment]
@phated Yeah, there probably should be a mode to represent the oneway token. It just felt more like a flag to me. The idea being that I'd check for the void type in a type check pass I'm working on #3.

**Comment by phated** [comment]
@kevinbgreene alright, so are changes occurring for this PR?

**Comment by phated** [comment]
@kevinbgreene are further changes coming here?

**Comment by kevinbgreene** [comment]
@phated Yeah, further changes coming. Try to put them up soon... to require oneway to have void return type.

**Comment by kevinbgreene** [comment]
@phated This code has gotten stale. Created a new PR #31. Adding a new commit on top of this to throw if oneway is not followed by void. I didn't add a node for the oneway keyword as I can't think of how it offers value to a consuming code generator. It seems the flag is all we really need. Maybe we don't need that much. Just verify the void type.

**Pull request closed without merging**
