### PR TITLE
Improves handling of comments and leave comments in AST

### LINKED ISSUE #17: Handle block comments in construct bodies
Tracking issue from #14 

Currently, the parser doesn't handle:
```thrift
service Service1 {
    int test() /* */ throws (1: MyError err; 2: string test)
}
```

The fix for this might fit with #16

### PR DESCRIPTION
**Pull request by kevinbgreene**
Fixes #17 and adds #16 

  * Allows for inline block comments
  * Leaves comments in AST by associating them with closest node (with leading preference)

### CODE REVIEW

**Review by phated — CHANGES_REQUESTED** [review]
This currently fails `npm run build` because `createFieldDefinition` and `createStructDefinition` in `src/factory.ts` are missing `comments`

**Comment by phated** [comment]
Also, it would be helpful for me if the comments outside of constructs could be their own nodes in the AST.

**Comment by kevinbgreene** [comment]
@phated Oops, npm test passed. ts-node must still gen code if type checking fails. Will have to figure out how to make this strict.

**Comment by phated** [comment]
It seems trailing newlines are being stripped from the comments, which causes problems when I try to insert the expected output into a fixture thrift file.

**Comment by kevinbgreene** [comment]
@phated I want to keep this AST similarly structured to Babylon and tsc both of which associate comments with nodes. Practically there is almost always an association between a comment and a piece of syntax.

**Comment by phated** [comment]
@kevinbgreene I'm fine with them being associated to the nodes because I can work with that.  However, I need them comments to include whitespace (like newlines) to compare properly.

**Comment by phated** [comment]
Looks like a few other commits ended up in this branch. The changes look good though.

**Review by phated — APPROVED** [review]

**Comment by kevinbgreene** [comment]
@phated Something I was playing with was the idea that the value of CommentBlock would be an array of strings corresponding to lines. What do you think? I figure we'll need to do some formatting in the codegen either way.

**Comment by phated** [comment]
Oh, that's interesting.  Would the leading `*` be removed from:
```
/*
 * Comment line
 */
```

I was trying to combine the thrift file and "solution" for fixtures, which is why I needed whitespace support. Making each line an element in an array would require joining them with `os.EOL` in that solution.

**Comment by kevinbgreene** [comment]
Yeah, what I'm working with does something like this:
```
/**
 * Comment Line
 *     Indented comment line
 */
```
Would become:
```
[ 'Comment line', '    Indented comment line' ]
```
So it would remove all the '*' and '/' formatting but keep leading spaces otherwise. Probably putting too much thought into this. As I've been playing with Babylon and tsc it's been pretty easy to get them to drop comments from the AST in some situations. Not a primary concern.

**Comment by kevinbgreene** [comment]
Closing this and merging a branch I rebased on master. Some gnarly conflicts. New PR is #29

**Pull request closed without merging**
